### PR TITLE
Add contributing guidelines

### PR DESCRIPTION
**Pull request by weblancaster**
This PR is the first version of the contributing guidelines and will be used as a start point reference.

### CODE REVIEW

**Comment by colebemis** [comment]
Thanks so much for taking the time to write this! I'll take a more detailed look at this when I get home.

Btw, the `deploy/netlify` check will always fail right now so don't worry about that.

**Comment by weblancaster** [comment]
Sounds good, take your time.

Thanks for sharing the project.

**Comment by colebemis** [comment]
@weblancaster I made some minor changes. Can you look over my edits and just give me a 👍 if you think it's ready to merge? :tada:

**Comment by weblancaster** [comment]
Nice! thanks for making those changes and I believe it's good to go.

**Pull request merged**
